In [1]:
import pandas as pd

# WORKING WITH JSON

In [2]:
pd.read_json(r'C:\Users\ayush\PROJECTS\ML\dataset\train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [ ]:
# reading json data from the API 

pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-02,1788307201,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-02,1788307201,0.0387
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-02,1788307201,0.6890
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-02,1788307201,0.8380
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-02,1788307201,3.8400
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-02,1788307201,2.4900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-02,1788307201,0.1700
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-02,1788307201,0.2000
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-02,1788307201,0.2820
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-09-02,1788307201,0.2820

# WORKING WITH SQL

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# --- YOUR SPECIFIC CONNECTION DETAILS ---
USERNAME = "root"
PASSWORD = "your_password"  # 👈 Replace with your actual MySQL root password use %40 for @
HOST = "localhost"  # Or 'localhost'
PORT = "3306"
DATABASE = "world"  # 👈 Replace with the database name created by your .sql file

# 1. Create the database engine
connection_string = (
    # If PASSWORD is empty or has a typo:
 f"mysql+pymysql://root:{PASSWORD}@{HOST}:{PORT}/{DATABASE}"
)
engine = create_engine(connection_string)

# 2. Test the connection & load a table into a Pandas DataFrame
table_name = "city"  # 👈 Replace with one of your table names
dfsql = pd.read_sql(f"SELECT * FROM {table_name};", con=engine)

# 3. View the dataset
dfsql.head()

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

# WORKING WITH APIS

In [3]:
import pandas as pd 
import requests

In [22]:
import requests

url = "https://api.themoviedb.org/3/movie/top_rated"

params = {
    "api_key": "f49147cedc457465c1cce77a8383bed0",
    "language": "en-US",
    "page": 1
}

try:
    response = requests.get(url, params=params, timeout=10)

    print(response.status_code)
    print(response.json())

except requests.exceptions.RequestException as e:
    print("Error:", e)

Error: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))